//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_menadzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokoje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pokoje()
        {
            this.rezerwacje = new HashSet<rezerwacje>();
        }
    
        public int nr_pokoju { get; set; }
        public string liczba_osob { get; set; }
        public decimal cena { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezerwacje> rezerwacje { get; set; }
    }
}
