//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_menadzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pracownicy
    {
        public int id_pracownika { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }







        /// <summary>
        /// Funkcja towrz¹ca login u¿ytkownika, poprzez po³¹czenie pierwszej litery iminia i nazwiska
        /// </summary>
        public void Login()
        {
            login = imie.Substring(0, 1).ToLower() + nazwisko.ToLower();
        }




    }
}
