//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_menadzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezerwacje
    {
        public int id_rezerwacji { get; set; }
        public System.DateTime od { get; set; }
        public System.DateTime @do { get; set; }
        public int nr_pokoju { get; set; }
        public int id_klienta { get; set; }
        public decimal koszt { get; set; }
        public string rodzaj_platnosci { get; set; }

        public virtual klienci klienci { get; set; }
        public virtual pokoje pokoje { get; set; }
    }
}
